project:
  type: book
  output-dir: docs


book:
  title: "Temporal and seasonal trends in bovine herds and bovine tuberculosis breakdowns in Ireland (2008-current)"
  author: 
  - name: Jamie Madden (CVERA)
    email: jamie.madden@ucd.ie
  date: 2025-02-05
  date-modified: last-modified
  date-format: DD MMM YYYY
  chapters:
    - index.qmd
    - part: "Policy timeline plot"
      chapters: 
        - timeline_policy.qmd
    - part: "Brief summary overview"
      chapters: 
        - summary_page.qmd
    - part: "Demographics"
      chapters: 
        - demographics.qmd
    - part: "bTB cases"
      chapters: 
        - case_numbers.qmd
    - part: "Lesion prevalence"
      chapters:
        - reactor_lesion_skin_gif_seperately.qmd
        - lesion_prevalence_trends.qmd
    - part: "Breakdowns (BDs)"
      chapters:
        - breakdown_page.qmd 
    - part: "Time series analysis"
      chapters: 
       - time_series.qmd
    - part: "Aggregated case count model"
      chapters: 
       - agg_cases_poisson_NB_model.qmd
    - part: "SICTT test-type seasonality"
      chapters:
        - sictt_test_types.qmd 
    - part: "CVERA publications"
      chapters:
        - publications.qmd
  search:
    location: sidebar # i dont think navbar works in book (only website)
    type: overlay
  page-navigation: true  # navigate option at bottom of page to next or previous page
  repo-url: https://github.com/j-madden-m/Irish_bTB_trends
  site-url: https://github.com/j-madden-m/Irish_bTB_trends
  #sharing: [twitter, linkedin]
  #reader-mode: true
  sidebar:
    background: "#4E5D6C"   
    foreground: "#FFFFFF"  
    logo: figures/logo_plot.png
    collapse-level: 1


bibliography: references.bib

format:
  html:
    grid:
      margin-width: 125px
    theme: flatly
    css: style.css
    highlight-style:  monokai 
    number-sections: true #you need this for cross referencing
    top-level-division: chapter
    page-layout: full
    toc: true
    #toc-location: left  # Equivalent to `toc_float: true`
    code-fold: false      # Equivalent to `code_folding: show`
    #cover-image: cover_plot.png


  # need to update ERROR: Your TexLive version is not updated enough to connect 
  # to the remote repository and download packages. Please update your installation of TexLive or TinyTex
  #pdf:
  #  documentclass: scrreprt

editor: visual

execute:
  cache: false  # Ensures inline R in YAML updates correctly
knitr:
  opts_knit:
    root.dir: "D:/Files/bTB_breakdown_trends_paper"
    
    
