# CVERA related bTB publications {#sec-publications}

------------------------------------------------------------------------

```{r}
#| label: global-options
#| include: false
# Center figures (alternative approach in Quarto)
knitr::opts_chunk$set(fig.align = "center")
# like this: #| fig-align: center
```

```{r}
#| label: readin-data
#| include: false
source("R_files/read_in_quarto_trends.R")
publications_df <- read_csv(paste0("data/edited_output/publications_df.csv")) 
```


$~$ $~$

## List of publications

Below is a list of bTB related publications from [CVERA](https://www.ucd.ie/cvera/) (from 1990 to `r (publications_df$check_date)[1]` (date the database was last accessed)). This also encompasses publications that may not be directly from CVERA (e.g., where a CVERA member is only a co-author on the publication, the list also includes publications from the [Tuberculosis Diagnostics & Immunology Research Laboratory](https://www.ucd.ie/vetmed/research/researchthemes/veterinaryepidemiologyandnationaldiseasecontrol/) in UCD).

Thanks to Dan Collins for maintaining the list.

Use the **search bar** in the table heading to search by any word.

$~$ $~$


```{r}
#| label: tbl-publications
#| tbl-cap: "bTB related CVERA publications"
#| include: TRUE
#| echo: FALSE
#| eval: TRUE
#| warning: FALSE
#| message: FALSE

library(DT)
publications_df <- publications_df %>% 
  select(-check_date)
datatable(publications_df,
          caption = 'Table 1: bTB related CVERA publications (ordered by most recent).',
          escape = FALSE,
          colnames = c('Year' = 'year_of_publication',
                       "Title" = "title",
                       "Full reference" = "reference",
                       "Link (if available)" = "Link"),
          options = list(pageLength = 50))
```




$~$ $~$

------------------------------------------------------------------------

$~$ $~$

------------------------------------------------------------------------